language: node_js
node_js:
  - "5.11"

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools
  - npm install actions-on-google
  - npm install firebase-admin
  - npm install firebase-functions

script:
  # TODO: test
  - firebase deploy --token=${FIREBASE_API_TOKEN}